version: "3.1"

services:
  mysql-db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASSWORD}
    ports:
    - 3306:3306
    volumes:
      - webflix:/var/lib/mysql

volumes:
  webflix: